language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - DOCTRINE_VERSION=v1.2.* ZEND_VERSION=2.1* DESARROLLA_VERSION=1.5.*
  - DOCTRINE_VERSION=v1.3.* ZEND_VERSION=2.1* DESARROLLA_VERSION=1.5.*
  - DOCTRINE_VERSION=1.4.*@dev ZEND_VERSION=2.1* DESARROLLA_VERSION=1.5.*
  - DOCTRINE_VERSION=v1.2.* ZEND_VERSION=2.2* DESARROLLA_VERSION=1.5.*
  - DOCTRINE_VERSION=v1.3.* ZEND_VERSION=2.2* DESARROLLA_VERSION=1.5.*
  - DOCTRINE_VERSION=1.4.*@dev ZEND_VERSION=2.2* DESARROLLA_VERSION=1.5.*
  - DOCTRINE_VERSION=v1.2.* ZEND_VERSION=2.3*@dev DESARROLLA_VERSION=1.5.*
  - DOCTRINE_VERSION=v1.3.* ZEND_VERSION=2.3*@dev DESARROLLA_VERSION=1.5.*
  - DOCTRINE_VERSION=1.4.*@dev ZEND_VERSION=2.3*@dev DESARROLLA_VERSION=1.5.*
  - DOCTRINE_VERSION=v1.2.* ZEND_VERSION=2.1* DESARROLLA_VERSION=1.6.*
  - DOCTRINE_VERSION=v1.3.* ZEND_VERSION=2.1* DESARROLLA_VERSION=1.6.*
  - DOCTRINE_VERSION=1.4.*@dev ZEND_VERSION=2.1* DESARROLLA_VERSION=1.6.*
  - DOCTRINE_VERSION=v1.2.* ZEND_VERSION=2.2* DESARROLLA_VERSION=1.6.*
  - DOCTRINE_VERSION=v1.3.* ZEND_VERSION=2.2* DESARROLLA_VERSION=1.6.*
  - DOCTRINE_VERSION=1.4.*@dev ZEND_VERSION=2.2* DESARROLLA_VERSION=1.6.*
  - DOCTRINE_VERSION=v1.2.* ZEND_VERSION=2.3*@dev DESARROLLA_VERSION=1.6.*
  - DOCTRINE_VERSION=v1.3.* ZEND_VERSION=2.3*@dev DESARROLLA_VERSION=1.6.*
  - DOCTRINE_VERSION=1.4.*@dev ZEND_VERSION=2.3*@dev DESARROLLA_VERSION=1.6.*
  - DOCTRINE_VERSION=v1.2.* ZEND_VERSION=2.1* DESARROLLA_VERSION=1.7.*
  - DOCTRINE_VERSION=v1.3.* ZEND_VERSION=2.1* DESARROLLA_VERSION=1.7.*
  - DOCTRINE_VERSION=1.4.*@dev ZEND_VERSION=2.1* DESARROLLA_VERSION=1.7.*
  - DOCTRINE_VERSION=v1.2.* ZEND_VERSION=2.2* DESARROLLA_VERSION=1.7.*
  - DOCTRINE_VERSION=v1.3.* ZEND_VERSION=2.2* DESARROLLA_VERSION=1.7.*
  - DOCTRINE_VERSION=1.4.*@dev ZEND_VERSION=2.2* DESARROLLA_VERSION=1.7.*
  - DOCTRINE_VERSION=v1.2.* ZEND_VERSION=2.3*@dev DESARROLLA_VERSION=1.7.*
  - DOCTRINE_VERSION=v1.3.* ZEND_VERSION=2.3*@dev DESARROLLA_VERSION=1.7.*
  - DOCTRINE_VERSION=1.4.*@dev ZEND_VERSION=2.3*@dev DESARROLLA_VERSION=1.7.*

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer require --no-update phpunit/phpunit:* mikey179/vfsStream:1.3.*@dev satooshi/php-coveralls:dev-master phpunit/phpcov:2.0.*@dev doctrine/cache:${DOCTRINE_VERSION} zendframework/zend-cache:${ZEND_VERSION} desarrolla2/cache:${DESARROLLA_VERSION} zetacomponents/cache:*
  - php vendor/autoload.php
  - mkdir -p build/logs

script:
  - phpunit --configuration travis.phpunit.xml.dist --colors --verbose

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: false
